cask_args appdir: "/Applications"

tap 'homebrew/bundle'
tap 'caskroom/cask'
tap 'homebrew/services'

brew 'elixir'
brew 'fd'
brew 'fish'
brew 'fzf'
brew 'git'
brew 'htop'
brew 'neovim'
brew 'node'
brew 'nvm'
brew 'pipenv'
brew 'postgres'
brew 'precommit'
brew 'pyenv'
brew 'python3'
brew 'reattach-to-user-namespace'
brew 'rippgrep'
brew 'the_silver_searcher'
brew 'tmux'
brew 'todo-txt'
brew 'tree'
brew 'zlib'

cask 'anki'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'keepingyouawake'
cask 'private-internet-access'
cask 'sktech'
cask 'slack'
cask 'spectacle'
cask 'visual-studio-code'
